application:
  subdomain: motrix
  multi_instance: true
  background_task: true
  upstreams:
    - location: /
      backend: http://server:8080/
  public_path:
    - /
services:
  server:
    # motrixapp/motrix-server:2.0.0-beta.19
    # upstream: motrixapp/motrix-server:2.0.0-beta.19
    image: registry.lazycat.cloud/czyt/motrixapp/motrix-server:0a3f711627540366
    user: root
    environment:
      - MOTRIX_DATA_DIR=/data
      - MOTRIX_TEMP_DIR=/data/tmp
      - MOTRIX_PLUGIN_DIR=/data/plugins
      - MOTRIX_DEFAULT_SAVE_DIR=/downloads
      - MOTRIX_ALLOWED_SAVE_DIRS=/downloads
      - MOTRIX_MDXP_HOST=0.0.0.0
      - MOTRIX_MDXP_PORT=16801
      - MOTRIX_OPERATOR_TOKEN={{.U.operator_token}}
      - MOTRIX_PUBLIC_URL=https://{{.S.AppDomain}}
    binds:
      - /lzcapp/var/data:/data
      - /lzcapp/run/mnt/home/{{.U.download_dir}}:/downloads
ext_config:
  enable_document_access: true
