package: community.lazycat.app.motrix
version: 2.0.0-beta.28
name: Motrix
description: "A modern download manager that supports all platforms. Built with Golang and Flutter."
min_os_version: 1.5.0
author: agalwood
license: MIT
homepage: https://github.com/agalwood/Motrix
locales:
  en:
    name: "Motrix"
    description: "A modern download manager that supports all platforms. Built with Golang and Flutter."
  zh:
    name: "Motrix"
    description: "简洁易用、功能丰富的现代下载管理器，支持 HTTP、BT、磁力链等协议。"
permissions:
  required:
    - net.internet
    - document.read
    - document.write
